feat: add banner dynamic data
anshikasharma148/intern-ecommerce-project pull request #2
Opened 2024-06-13 09:09 UTC by anshikasharma148

2024-06-13 09:11 UTC, Himanshu7614 commented on app/components/Hero.tsx
> +// src/components/Hero.tsx
change file name Hero to "slider"

2024-06-13 09:12 UTC, Himanshu7614 commented on app/components/Nav.tsx
> -import { useState, useEffect } from 'react';
change file name nav to "header.tsx"

2024-06-13 09:14 UTC, Himanshu7614 commented on app/components/Nav.tsx
>  import logo from 'E:/intern-ecommerce-project/public/logo.png';
Do not use the complete path name. You can use './logo.png'; it will work fine and is the correct way to reference the image path.

2024-06-13 09:14 UTC, Himanshu7614 commented on app/components/Nav.tsx
> +            {/* Logo Container */}
remove this types of line

2024-06-13 09:14 UTC, Himanshu7614 commented on app/components/Nav.tsx
> +            {/* Links Container */}
remove this line

2024-06-13 09:16 UTC, Himanshu7614 commented on app/components/Nav.tsx
> +                    stroke-linecap="round"
Check how to write stroke-linecap, stroke-linejoin, and stroke-width. Verify the correct way to use these parameters.

2024-06-13 09:17 UTC, Himanshu7614 requested changes
check comments on code

2024-06-13 09:28 UTC, anshikasharma148 commented on app/components/Hero.tsx
> +// src/components/Hero.tsx
ok

2024-06-18 09:03 UTC, Himanshu7614 approved these changes

2024-06-18 09:03 UTC, merged